# Generated by Django 2.0.3 on 2019-06-19 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=3)),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futground.Ground')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('starting_time', models.IntegerField()),
                ('ending_time', models.IntegerField()),
                ('reserved_date', models.DateField()),
                ('ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futground.Ground')),
            ],
        ),
    ]
