# Generated by Django 2.0.3 on 2019-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='starting_time',
            field=models.TimeField(),
        ),
    ]
